/** Lowercase local-parts blocked at registration (deliverability / reserved address patterns). */
const RESERVED = new Set<string>([
  "abuse",
  "admin",
  "administrator",
  "all",
  "api",
  "app",
  "apps",
  "billing",
  "contact",
  "daemon",
  "dev",
  "dns",
  "ftp",
  "help",
  "hostmaster",
  "imap",
  "info",
  "localhost",
  "mail",
  "mailer-daemon",
  "mailerdaemon",
  "marketing",
  "news",
  "noc",
  "noreply",
  "no-reply",
  "null",
  "pop",
  "postmaster",
  "privacy",
  "root",
  "sales",
  "security",
  "smtp",
  "staff",
  "support",
  "sysadmin",
  "system",
  "team",
  "undefined",
  "usenet",
  "uucp",
  "webmaster",
  "welcome",
  "www",
]);

export function isReservedUsername(localPartLower: string): boolean {
  return RESERVED.has(localPartLower);
}
